#!/usr/bin/env python
import os
import sys

def get_files(extension):
    extension_files = []
    for i in os.listdir("."):
        if i.endswith(extension):
            extension_files.append(i)
    extension_files.sort()
    return extension_files

def rename_files(list_files, prefix, iteration_start, num_digits, extension):
    iteration = int(iteration_start)
    for i in list_files:
        str_iteration = str(iteration).zfill(int(num_digits))
        os.rename(i, prefix+str_iteration+"."+extension)
        print (prefix+str_iteration+"."+extension)
        iteration = iteration+1

def main():
    if len(sys.argv) == 1:
        print "photo-rename <prefix> <itertion-start> <num-digits> <extension>"
        sys.exit(1)

    prefix = sys.argv[1]
    iteration_start = sys.argv[2]
    num_digits = sys.argv[3]
    extension = sys.argv[4]

    list_files = get_files(extension)
    rename_files(list_files, prefix, iteration_start, num_digits, extension)

if __name__ == "__main__":
    main()
